[masters]
<master-node-1-name> ansible_host=<ip>
<master-node-2-name> ansible_host=<ip>
<master-node-3-name> ansible_host=<ip>

[masters:vars]
ansible_user=username
ansible_password=password

[workers]
<worker-node-1-name> ansible_host=<ip>
<worker-node-2-name> ansible_host=<ip>

[workers:vars]
ansible_user=username 
ansible_password=password 
