apiVersion: v1
kind: Secret
metadata: 
  name: secret1
type: Opaque
data:
  username: <dXNlcm5hbWU= base64 encoded username> # dXNlcm5hbWU= equiv username
  password: <cGFzc3dvcmQ= base64 encoded password> # cGFzc3dvcmQ= equiv password
# or use stringData if base64 not preferred
stringData:
  username: username
  password: password